version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - '3000:3000'
    networks:
      - tasknet

  frontend:
    container_name: frontend
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '8080:5173'
    command: bash -c "npm install && npm run dev -- --host"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - tasknet

volumes:
  frontend_node_modules:

networks:
  tasknet:
    driver: bridge
